Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,6 +23,13 @@ jobs:
         run: |
           echo "Checking required secrets..."
 
+          if [ -z "${{ secrets.DEPLOY_USER }}" ]; then
+            echo "❌ DEPLOY_USER is EMPTY or MISSING"
+            exit 1
+          else
+            echo "✅ DEPLOY_USER is set"
+          fi
+
           if [ -z "${{ secrets.DEPLOY_HOST }}" ]; then
             echo "❌ DEPLOY_HOST is EMPTY or MISSING"
             exit 1
@@ -30,12 +37,7 @@ jobs:
             echo "✅ DEPLOY_HOST is set"
           fi
 
-          if [ -z "${{ secrets.DEPLOY_USER }}" ]; then
-            echo "❌ DEPLOY_USER is EMPTY or MISSING"
-            exit 1
-          else
-            echo "✅ DEPLOY_USER is set"
-          fi
+          
 
           if [ -z "${{ secrets.DEPLOY_SSH_KEY }}" ]; then
             echo "❌ DEPLOY_SSH_KEY is EMPTY or MISSING"
